name: youtube_box_thumbnail
description: "Package used to display video thumbnail box from youtube"
version: 1.0.0+1
homepage: https://sondv301.github.io/
repository: https://github.com/sondv301/youtube_box_thumbnail

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

